first_game/characters/urls.py
from django.urls import path

from . import views

app_name= 'characters'
urlpatterns = [
    ###GET
    #ex: /character/
    path('', views.IndexView.as_view(), name='index'),
    #ex: /character/1
    path('<int:character_id>/', views.details, name='details'),
    #ex: /character/1/armor
    path('<int:character_id>/armor/', views.armor, name='armor'),
    #ex: /character/1/armor/1
    path('<int:character_id>/armor/<int:armor_id>/', views.armor_details, name='armor_details'),
    ###POST
    #ex: /character/1/fight
    path('<int:character_id>/fight', views.fight, name='fight')
]

first_game/first_game/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('characters/', include('characters.urls')),
    path('admin/', admin.site.urls),
]

first_game/characters/models.py
from django.db import models

# Create your models here.
class Character(models.Model):
    name = models.CharField(max_length=20)
    level = models.IntegerField(default=1)
    nextLevelExp = models.IntegerField(default=100)
    currentExp = models.IntegerField(default=0)
    maxHealth = models.IntegerField(default=0)
    currentHealth = models.IntegerField(default=0)
    maxMana = models.IntegerField(default=0)
    currentMana = models.IntegerField(default=0)
    attack = models.IntegerField(default=0)
    defense = models.IntegerField(default=0)
    '''
    name = models.CharField(max_length=20)
    level = models.IntegerField(default=1)
    nextLevelExp = models.IntegerField(default=100)
    currentExp = models.IntegerField(default=0)
    maxHealth = models.IntegerField(default= (10 * Character.level))
    currentHealth = models.IntegerField(default=maxHealth)
    maxMana = models.IntegerField(default= (5 * level))
    currentMana = models.IntegerField(default=maxMana)
    attack = models.IntegerField(default= (3 * level))
    defense = models.IntegerField(default=level)
    '''

    def __str__(self):
        return self.name

class Armor(models.Model):
    belongs_to = models.ForeignKey(to=Character, on_delete=models.CASCADE)
    name = models.CharField(max_length=20)
    attack = models.IntegerField(default=0)
    defense = models.IntegerField(default=0)

    def __str__(self):
        return self.name


class Weapon(models.Model):
    belongs_to = models.ForeignKey(to=Character, on_delete=models.CASCADE)
    name = models.CharField(max_length=20)
    attack = models.IntegerField(default=0)
    defense = models.IntegerField(default=0)

    def __str__(self):
        return self.name

class Skill(models.Model):
    belongs_to = models.ForeignKey(to=Character, on_delete=models.CASCADE)
    name = models.CharField(max_length=20)
    attack = models.IntegerField(default=0)
    cost = models.IntegerField(default=0)

    def __str__(self):
        return self.name
    

first_game/characters/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic

from .models import Character, Armor, Weapon, Skill

# Create your views here.
class IndexView(generic.ListView):
    template_name = 'characters/index.html'
    context_object_name = 'character_list'

    def get_queryset(self):
        '''return list of characters'''
        return Character.objects.all()

def details (request, character_id):
    #get Character
    character = get_object_or_404(Character, pk=character_id)
    
    #getArmor
    try:
        armor = Armor.objects.get(belongs_to=character_id) 
    except Armor.DoesNotExist:
        armor = None
    #getWeapon
    try:
        weapon = Weapon.objects.get(belongs_to=character_id)
    except Weapon.DoesNotExist:
        weapon = None
    #get Skill
    try:
        skill = Skill.objects.get(belongs_to=character_id)
    except Skill.DoesNotExist:
        skill = None

    context = {'character': character,
                'armor': armor,
                'weapon': weapon,
                'skill': skill
                }
    return render(request, 'characters/detail.html', context)

def armor(request, character_id):
    armor_list = Armor.objects.all().filter(pk=1)
    context = {'armor_list': armor_list}
    return render(request, 'armors/index.html', context)

def armor_details(request, character_id, armor_id):
    armor = get_object_or_404(Armor, pk=armor_id, fk=character_id)
    return render(request, 'armors/detail.html', {'armor': armor})

def fight(request, character_id):
    character = get_object_or_404(Character, pk=character_id)
    character.currentExp += 5
    character.save()
    return HttpResponseRedirect(reverse('characters:details', args=(character.id,)))

first_game/characters/templates/armors/detail.html
<h1>{{ armor }}</h1>

first_game/characters/templates/armors/index.html
{% if armor_list %}
    <ul>
    {% for armor in armor_list %}
        <li>{{ armor.name }} - ID.{{ armor.id }} - {{armor.belongs_to}}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No armors are available.</p>
{% endif %}

first_game/characters/templates/characters/detail.html
<h1>{{ character }}</h1>

<ul>
    <li>Name: {{ character.name }}</li>
    <li>Level: {{ character.level }}</li>
    <li>Exp: {{ character.currentExp }} / {{ character.nextLevelExp }}</li>
    <li>Health: {{ character.currentHealth }} / {{ character.maxHealth }}</li>
    <li>Mana: {{ character.currentMana }} / {{ character.maxMana }}</li>
    <li>Attack: {{ character.attack }}</li>
    <li>Defense: {{ character.defense }}</li>
    <li>Armor:  {% if character.armor_set %}
                    {% for armor in character.armor_set.all %}
                        {{ armor.name }}
                        <ul>
                            <li>Attack: {{armor.attack}}</li>
                            <li>Defense: {{armor.defense}}</li>
                        </ul>
                    {% endfor%}
                {% else %}
                    None
                {% endif %}</li>
    <li>Weapon: {% if weapon %}
                    {{ weapon.name }}
                    <ul>
                        <li>Attack: {{weapon.attack}}</li>
                        <li>Defense: {{weapon.defense}}</li>
                    </ul>
                {% else %}
                    None
                {% endif %}</li>
    <li>Skill: {% if skill %}
                    {{ skill.name }}
                    <ul>
                        <li>Attack: {{skill.attack}}</li>
                        <li>Defense: {{skill.defense}}</li>
                    </ul>
                {% else %}
                    None
                {% endif %}</li>
</ul>

<h3><a href="{% url 'characters:fight' character.id%}">Fight!</a></h3>

first_game/characters/templates/characters/index.html
{% if character_list %}
    <ul>
    {% for character in character_list %}
        <li><a href="{% url 'characters:details' character.id%}">{{ character.name }} - Lv.{{ character.level }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No characters are available.</p>
{% endif %}